buildscript {
    ext.kotlin_version = '2.1.0' // Required for Firebase v9+
    repositories {
        google()
        mavenCentral()
        // 👇 Required for Flutter dependencies like flutter_embedding_debug
        maven { url "https://storage.googleapis.com/download.flutter.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.3'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // 👇 Also add here for plugins that reference Flutter artifacts
        maven { url "https://storage.googleapis.com/download.flutter.io" }
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
