org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
kotlin.jvm.target=17
# For Mac
; org.gradle.java.home=/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home
# For Windows (uncomment the next line if building on Windows)
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
; /opt/homebrew/Cellar/openjdk@17/17.0.15/libexec/openjdk.jdk/Contents/Home