org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
kotlin.jvm.target=17

# For Mac
; org.gradle.java.home=/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home
# For Windows
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
; /opt/homebrew/Cellar/openjdk@17/17.0.15/libexec/openjdk.jdk/Contents/Home

# 🔥 REQUIRED FOR GOOGLE PLAY 16KB MEMORY PAGE SIZE SUPPORT
android.experimental.enable16kPages=true
android.jvmti.enable=true
android.ndkVersion=25.2.9519653
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
