// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZcJeBEHZt8ons81Pc135o6kCAGxAAUdY',
    appId: '1:359242778179:web:ceeb1d43fa0e199714f6f6',
    messagingSenderId: '359242778179',
    projectId: 'dar-al-safwa-96fc0',
    authDomain: 'dar-al-safwa-96fc0.firebaseapp.com',
    storageBucket: 'dar-al-safwa-96fc0.firebasestorage.app',
    measurementId: 'G-NXV5Q1RG5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67CkS9v-jrQfKZCf_rM4UwRwH8euZdf4',
    appId: '1:359242778179:android:0da7216b54e6ef0b14f6f6',
    messagingSenderId: '359242778179',
    projectId: 'dar-al-safwa-96fc0',
    storageBucket: 'dar-al-safwa-96fc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOsV_MKHunreR1Dy8SIhay5Ys1cC9WSQ',
    appId: '1:359242778179:ios:cbaeb390ce9e2ed714f6f6',
    messagingSenderId: '359242778179',
    projectId: 'dar-al-safwa-96fc0',
    storageBucket: 'dar-al-safwa-96fc0.firebasestorage.app',
    iosBundleId: 'com.example.darAlSafwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOOsV_MKHunreR1Dy8SIhay5Ys1cC9WSQ',
    appId: '1:359242778179:ios:cbaeb390ce9e2ed714f6f6',
    messagingSenderId: '359242778179',
    projectId: 'dar-al-safwa-96fc0',
    storageBucket: 'dar-al-safwa-96fc0.firebasestorage.app',
    iosBundleId: 'com.example.darAlSafwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZcJeBEHZt8ons81Pc135o6kCAGxAAUdY',
    appId: '1:359242778179:web:0ed3effdbc33035414f6f6',
    messagingSenderId: '359242778179',
    projectId: 'dar-al-safwa-96fc0',
    authDomain: 'dar-al-safwa-96fc0.firebaseapp.com',
    storageBucket: 'dar-al-safwa-96fc0.firebasestorage.app',
    measurementId: 'G-0Q0KJCDJ4Z',
  );
}
