// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKL01-PPK2rlhGjwFCK-V6JV6EtwNkYk',
    appId: '1:961349068661:web:9f07200674806e8de8553c',
    messagingSenderId: '961349068661',
    projectId: 'dar-al-safwa-uae',
    authDomain: 'dar-al-safwa-uae.firebaseapp.com',
    databaseURL: 'https://dar-al-safwa-uae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dar-al-safwa-uae.firebasestorage.app',
    measurementId: 'G-RXXSN0TPVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRWoCgF777mRLB4Tbo9RkhuOAPzN8rhzA',
    appId: '1:961349068661:android:7716650debfb343be8553c',
    messagingSenderId: '961349068661',
    projectId: 'dar-al-safwa-uae',
    databaseURL: 'https://dar-al-safwa-uae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dar-al-safwa-uae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdgXxICK_0qRcQGjMJ6jwYHGPGoL6TKus',
    appId: '1:961349068661:ios:d9a719dac6f589e2e8553c',
    messagingSenderId: '961349068661',
    projectId: 'dar-al-safwa-uae',
    databaseURL: 'https://dar-al-safwa-uae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dar-al-safwa-uae.firebasestorage.app',
    androidClientId: '961349068661-0fjbomrve552u4vtpmi8gvknstn7btiu.apps.googleusercontent.com',
    iosClientId: '961349068661-r2utatjsi00r545enqdtb80fa0204ekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.darAlSafwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdgXxICK_0qRcQGjMJ6jwYHGPGoL6TKus',
    appId: '1:961349068661:ios:d9a719dac6f589e2e8553c',
    messagingSenderId: '961349068661',
    projectId: 'dar-al-safwa-uae',
    databaseURL: 'https://dar-al-safwa-uae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dar-al-safwa-uae.firebasestorage.app',
    androidClientId: '961349068661-0fjbomrve552u4vtpmi8gvknstn7btiu.apps.googleusercontent.com',
    iosClientId: '961349068661-r2utatjsi00r545enqdtb80fa0204ekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.darAlSafwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKL01-PPK2rlhGjwFCK-V6JV6EtwNkYk',
    appId: '1:961349068661:web:fd4aaa9d7324cebce8553c',
    messagingSenderId: '961349068661',
    projectId: 'dar-al-safwa-uae',
    authDomain: 'dar-al-safwa-uae.firebaseapp.com',
    databaseURL: 'https://dar-al-safwa-uae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dar-al-safwa-uae.firebasestorage.app',
    measurementId: 'G-ZZ62KPRKSJ',
  );

}